#!/bin/bash
#
# PRESS ESC KEY to exit slideshow.
#
# Slideshow for MAE hallway displays.
# Slides go in ~pi/Downloads/
#
# Requires feh:
#   sudo apt-get update
#   sudo apt-get install feh
#
/usr/bin/feh -Y -x -q -D 15 -B black -F -Z -z -r /home/pi/Downloads

