#!/bin/bash
#
# PRESS ESC KEY to exit slideshow.
#
# Slideshow for MAE hallway displays.
#
# Requires feh:
#   sudo apt-get update
#   sudo apt-get install feh
#
# Root directory for all the slides we want to display:
### COVID state of emergency ended 2023-02-28
### SLIDES_ROOT=/home/pi/slides/COVID_emergency
SLIDES_ROOT=/home/pi/slides/MAE_default

/usr/bin/feh -Y -x -q -D 15 -B black -F -Z -z -r "$SLIDES_ROOT"

